name = "AstroRegistry"
uuid = "8b298450-6d11-4dee-beb0-0991d9ed6516"
repo = "git@github.com:astro-group-bristol/AstroRegistry"

[packages]
1f539516-e6d2-4f24-ab09-50f3ac3c4a5a = { name = "GeodesicBase", path = "G/GeodesicBase" }
1f548346-32cf-4117-8ecc-304cf7418187 = { name = "GeodesicTracer", path = "G/GeodesicTracer" }
2b1461c5-fb25-4b94-b31c-0acab88ddff2 = { name = "CarterBoyerLindquist", path = "C/CarterBoyerLindquist" }
42910a5e-bdf1-4870-a538-dfa35571a56d = { name = "ComputedGeodesicEquations", path = "C/ComputedGeodesicEquations" }
7f85384a-175b-40eb-971c-1f0b02ab1b9a = { name = "AccretionGeometry", path = "A/AccretionGeometry" }
dcac253f-9cde-4166-a841-20d11661ef48 = { name = "GeodesicRendering", path = "G/GeodesicRendering" }
