name = "AstroRegistry"
uuid = "8b298450-6d11-4dee-beb0-0991d9ed6516"
repo = "git@github.com:astro-group-bristol/AstroRegistry"

[packages]
1f539516-e6d2-4f24-ab09-50f3ac3c4a5a = { name = "GeodesicBase", path = "G/GeodesicBase" }
1f548346-32cf-4117-8ecc-304cf7418187 = { name = "GeodesicTracer", path = "G/GeodesicTracer" }
7f85384a-175b-40eb-971c-1f0b02ab1b9a = { name = "AccretionGeometry", path = "A/AccretionGeometry" }
